const DIRECTORY_SEPARATOR = '_'
const EXPLORER_TREE_ITEM_CONTEXT_VALUE = 'github-workflows-explorer-item'
const EXPLORER_TREE_ITEM_FOLDER_ICON = 'folder'
const COULD_NOT_LOAD_WORKFLOWS_EXPLORER = 'Could not load workflows explorer.'

module.exports = {
    DIRECTORY_SEPARATOR,
    EXPLORER_TREE_ITEM_CONTEXT_VALUE,
    EXPLORER_TREE_ITEM_FOLDER_ICON,
    COULD_NOT_LOAD_WORKFLOWS_EXPLORER
}